/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BodyDoublerOO;

/**
 *
 * @author GVE Rouse
 */
public class EditSessionGUI extends javax.swing.JFrame {

    /**
     * Creates new form EditSessionGUI
     */
    public EditSessionGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeEditJL = new javax.swing.JLabel();
        sessionJScrollP = new javax.swing.JScrollPane();
        sessionsTable = new javax.swing.JTable();
        dateJL = new javax.swing.JLabel();
        dayJL = new javax.swing.JLabel();
        dayJComboB = new javax.swing.JComboBox<>();
        monthJL = new javax.swing.JLabel();
        monthJComboB = new javax.swing.JComboBox<>();
        yearJL = new javax.swing.JLabel();
        yearComboB = new javax.swing.JComboBox<>();
        timeJL = new javax.swing.JLabel();
        timeJComboB = new javax.swing.JComboBox<>();
        roomJL = new javax.swing.JLabel();
        roomJComboB = new javax.swing.JComboBox<>();
        maxPartJL = new javax.swing.JLabel();
        maxPartJComboB = new javax.swing.JComboBox<>();
        sessionIDJL = new javax.swing.JLabel();
        sessionIDComboB = new javax.swing.JComboBox<>();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeEditJL.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        welcomeEditJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeEditJL.setText("Edit Session");

        sessionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Session ID", "Date", "Time", "Location", "Max People", "Current People"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sessionJScrollP.setViewportView(sessionsTable);

        dateJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        dateJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateJL.setText("Date:");

        dayJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        dayJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayJL.setText("Day:");

        dayJComboB.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        dayJComboB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        monthJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        monthJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monthJL.setText("Month:");

        monthJComboB.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        monthJComboB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        monthJComboB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthJComboBActionPerformed(evt);
            }
        });

        yearJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        yearJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yearJL.setText("Year:");

        yearComboB.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        yearComboB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025" }));
        yearComboB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBActionPerformed(evt);
            }
        });

        timeJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        timeJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeJL.setText("Time:");

        timeJComboB.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        timeJComboB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00 am", "7:15 am", "7:30 am", "7:45 am", "8:00 am", "8:15 am", "8:30 am", "8:45 am", "9:00 am", "9:15 am", "9:30 am", "9:45 am", "10:00 am", "10:15 am", "10:30 am", "10:45 am", "11:00 am", "11:15 am", "11:30 am", "11:45 am", "12:00 pm", "12:15 pm", "12:30 pm", "12:45 pm", "1:00 pm", "1:15 pm", "1:30 pm", "1:45 pm", "2:00 pm", "2:15 pm", "2:30 pm", "2:45 pm", "3:00 pm", "3:15 pm", "3:30 pm", "3:45 pm", "4:00 pm", "4:15 pm", "4:30 pm", "4:45 pm", "5:00 pm", "5:15 pm", "5:30 pm", "5:45 pm", "6:00 pm", "6:15 pm", "6:30 pm", "6:45 pm", "7:00 pm", "7:15 pm", "7:30 pm", "7:45 pm", "8:00 pm", "8:15 pm", "8:30 pm", "8:45 pm", "9:00 pm", " " }));

        roomJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        roomJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomJL.setText("Room:");

        roomJComboB.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        roomJComboB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WZ401", "WZ402", "WZ403", "WZ405" }));

        maxPartJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        maxPartJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxPartJL.setText("Max Partcipants");

        maxPartJComboB.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        maxPartJComboB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));

        sessionIDJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        sessionIDJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sessionIDJL.setText("Session ID:");

        sessionIDComboB.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        sessionIDComboB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SES001", "SES002", "SES003", "SES004" }));

        confirmButton.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        confirmButton.setText("Confirm Edit");
        confirmButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sessionJScrollP)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(welcomeEditJL, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sessionIDJL, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sessionIDComboB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(536, 536, 536))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dateJL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(timeJL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(roomJL, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dayJL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(roomJComboB, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(timeJComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(23, 23, 23)
                                                .addComponent(monthJL, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(dayJComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maxPartJL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(maxPartJComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(monthJComboB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(yearJL, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yearComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeEditJL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sessionJScrollP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sessionIDJL)
                    .addComponent(sessionIDComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateJL)
                    .addComponent(dayJL)
                    .addComponent(dayJComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthJL)
                    .addComponent(monthJComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearJL)
                    .addComponent(yearComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeJL)
                    .addComponent(timeJComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomJL)
                            .addComponent(roomJComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxPartJL)
                            .addComponent(maxPartJComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(confirmButton)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monthJComboBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthJComboBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthJComboBActionPerformed

    private void yearComboBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearComboBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSessionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSessionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSessionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSessionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditSessionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel dateJL;
    private javax.swing.JComboBox<String> dayJComboB;
    private javax.swing.JLabel dayJL;
    private javax.swing.JComboBox<String> maxPartJComboB;
    private javax.swing.JLabel maxPartJL;
    private javax.swing.JComboBox<String> monthJComboB;
    private javax.swing.JLabel monthJL;
    private javax.swing.JComboBox<String> roomJComboB;
    private javax.swing.JLabel roomJL;
    private javax.swing.JComboBox<String> sessionIDComboB;
    private javax.swing.JLabel sessionIDJL;
    private javax.swing.JScrollPane sessionJScrollP;
    private javax.swing.JTable sessionsTable;
    private javax.swing.JComboBox<String> timeJComboB;
    private javax.swing.JLabel timeJL;
    private javax.swing.JLabel welcomeEditJL;
    private javax.swing.JComboBox<String> yearComboB;
    private javax.swing.JLabel yearJL;
    // End of variables declaration//GEN-END:variables
}
