/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BodyDoublerOO;

/**
 *
 * @author GVE Rouse
 */
public class RegisterMemberGUI extends javax.swing.JFrame {

    /**
     * Creates new form RegisterUserGUI
     */
    public RegisterMemberGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructJL = new javax.swing.JLabel();
        firstNameJL = new javax.swing.JLabel();
        firstNameJTextF = new javax.swing.JTextField();
        lNameJL = new javax.swing.JLabel();
        lNameJTextF = new javax.swing.JTextField();
        memberEmailJL = new javax.swing.JLabel();
        userEmailTextF = new javax.swing.JTextField();
        enterPWJL = new javax.swing.JLabel();
        memberPassword = new javax.swing.JPasswordField();
        askAgeJL = new javax.swing.JLabel();
        ageAskJTextF = new javax.swing.JTextField();
        studentIDJL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userIDNumberJTextF = new javax.swing.JTextPane();
        degreeJL = new javax.swing.JLabel();
        degreeJComboBox = new javax.swing.JComboBox<>();
        createUserJButon = new javax.swing.JButton();
        memberRegWelcomJL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 420));

        instructJL.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        instructJL.setText("To create your user account please fill in the follwoing infomation");

        firstNameJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        firstNameJL.setText("First name:");

        firstNameJTextF.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        firstNameJTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameJTextFActionPerformed(evt);
            }
        });

        lNameJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lNameJL.setText("Last name: ");

        lNameJTextF.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lNameJTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameJTextFActionPerformed(evt);
            }
        });

        memberEmailJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        memberEmailJL.setText("Email address: ");

        userEmailTextF.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        userEmailTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEmailTextFActionPerformed(evt);
            }
        });

        enterPWJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        enterPWJL.setText("Please enter a password:");

        memberPassword.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        askAgeJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        askAgeJL.setText("Age:");

        ageAskJTextF.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        ageAskJTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageAskJTextFActionPerformed(evt);
            }
        });

        studentIDJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        studentIDJL.setText("Student ID number:");

        userIDNumberJTextF.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(userIDNumberJTextF);

        degreeJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        degreeJL.setText("Please select your degree program:");

        degreeJComboBox.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        degreeJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCIS", "BFA", "BBIM", "BCA", "BA", "Other", " " }));

        createUserJButon.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        createUserJButon.setText("Create Account ");

        memberRegWelcomJL.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        memberRegWelcomJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        memberRegWelcomJL.setText("Welcome to the Member Registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(memberRegWelcomJL, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(createUserJButon, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(instructJL, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(studentIDJL, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(memberEmailJL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(userEmailTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lNameJL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lNameJTextF)
                            .addGap(59, 59, 59))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(firstNameJL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(firstNameJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(askAgeJL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ageAskJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(degreeJL, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(degreeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(enterPWJL, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(memberPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(memberRegWelcomJL)
                .addGap(18, 18, 18)
                .addComponent(instructJL)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameJL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNameJL)
                    .addComponent(lNameJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberEmailJL)
                    .addComponent(userEmailTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(askAgeJL)
                    .addComponent(ageAskJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentIDJL)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(degreeJL)
                    .addComponent(degreeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterPWJL)
                    .addComponent(memberPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(createUserJButon)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameJTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameJTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameJTextFActionPerformed

    private void ageAskJTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageAskJTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageAskJTextFActionPerformed

    private void lNameJTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameJTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameJTextFActionPerformed

    private void userEmailTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEmailTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userEmailTextFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterMemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterMemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterMemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterMemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterMemberGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageAskJTextF;
    private javax.swing.JLabel askAgeJL;
    private javax.swing.JButton createUserJButon;
    private javax.swing.JComboBox<String> degreeJComboBox;
    private javax.swing.JLabel degreeJL;
    private javax.swing.JLabel enterPWJL;
    private javax.swing.JLabel firstNameJL;
    private javax.swing.JTextField firstNameJTextF;
    private javax.swing.JLabel instructJL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lNameJL;
    private javax.swing.JTextField lNameJTextF;
    private javax.swing.JLabel memberEmailJL;
    private javax.swing.JPasswordField memberPassword;
    private javax.swing.JLabel memberRegWelcomJL;
    private javax.swing.JLabel studentIDJL;
    private javax.swing.JTextField userEmailTextF;
    private javax.swing.JTextPane userIDNumberJTextF;
    // End of variables declaration//GEN-END:variables
}
