/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BodyDoublerOO;

/**
 *
 * @author GVE Rouse
 */
public class RegisterAdminGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminRegisterGUI
     */
    public RegisterAdminGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPannel = new javax.swing.JPanel();
        welcomeAdminJL = new javax.swing.JLabel();
        adminInstructJL = new javax.swing.JLabel();
        fNameJL = new javax.swing.JLabel();
        adminFNameJTextF = new javax.swing.JTextField();
        lNameJL = new javax.swing.JLabel();
        lNameJTextF = new javax.swing.JTextField();
        emailJL = new javax.swing.JLabel();
        emailJTextF = new javax.swing.JTextField();
        pWJL = new javax.swing.JLabel();
        adminPWJTextF = new javax.swing.JTextField();
        departmentJL = new javax.swing.JLabel();
        roleJL = new javax.swing.JLabel();
        roleJComboBox = new javax.swing.JComboBox<>();
        departmentJComboBox = new javax.swing.JComboBox<>();
        createAccountJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 420));

        welcomeAdminJL.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        welcomeAdminJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeAdminJL.setText("Welcome to Admin Registration");

        adminInstructJL.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        adminInstructJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminInstructJL.setText("To create your admin account please fill in the boxes below");

        fNameJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        fNameJL.setText("First name:");

        adminFNameJTextF.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        adminFNameJTextF.setText("First name");

        lNameJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lNameJL.setText("Last name:");

        lNameJTextF.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        lNameJTextF.setText("last name");

        emailJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        emailJL.setText("Email address:");

        emailJTextF.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        emailJTextF.setText("exampleemail@autuni.ac.nz");

        pWJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        pWJL.setText("Please enter a password:");

        adminPWJTextF.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N

        departmentJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        departmentJL.setText("Department:");

        roleJL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        roleJL.setText("Role:");

        roleJComboBox.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        roleJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Staff", "Other" }));

        departmentJComboBox.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        departmentJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faculty", "Estates", "AUTSA" }));

        createAccountJButton.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        createAccountJButton.setText("Create Account");

        javax.swing.GroupLayout mainJPannelLayout = new javax.swing.GroupLayout(mainJPannel);
        mainJPannel.setLayout(mainJPannelLayout);
        mainJPannelLayout.setHorizontalGroup(
            mainJPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeAdminJL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainJPannelLayout.createSequentialGroup()
                .addGroup(mainJPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainJPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(adminInstructJL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainJPannelLayout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addGroup(mainJPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainJPannelLayout.createSequentialGroup()
                                    .addGroup(mainJPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainJPannelLayout.createSequentialGroup()
                                            .addComponent(roleJL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(mainJPannelLayout.createSequentialGroup()
                                            .addComponent(fNameJL, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(adminFNameJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(pWJL, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainJPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainJPannelLayout.createSequentialGroup()
                                            .addGap(62, 62, 62)
                                            .addComponent(lNameJL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(lNameJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(mainJPannelLayout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addComponent(departmentJL, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(departmentJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(adminPWJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(mainJPannelLayout.createSequentialGroup()
                                    .addComponent(emailJL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(emailJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(35, 35, 35)))
                    .addGroup(mainJPannelLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(createAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        mainJPannelLayout.setVerticalGroup(
            mainJPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPannelLayout.createSequentialGroup()
                .addComponent(welcomeAdminJL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminInstructJL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainJPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameJL)
                    .addComponent(adminFNameJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameJL)
                    .addComponent(lNameJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainJPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pWJL)
                    .addComponent(adminPWJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainJPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailJL))
                .addGap(38, 38, 38)
                .addGroup(mainJPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleJL)
                    .addComponent(departmentJL)
                    .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(createAccountJButton)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainJPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterAdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminFNameJTextF;
    private javax.swing.JLabel adminInstructJL;
    private javax.swing.JTextField adminPWJTextF;
    private javax.swing.JButton createAccountJButton;
    private javax.swing.JComboBox<String> departmentJComboBox;
    private javax.swing.JLabel departmentJL;
    private javax.swing.JLabel emailJL;
    private javax.swing.JTextField emailJTextF;
    private javax.swing.JLabel fNameJL;
    private javax.swing.JLabel lNameJL;
    private javax.swing.JTextField lNameJTextF;
    private javax.swing.JPanel mainJPannel;
    private javax.swing.JLabel pWJL;
    private javax.swing.JComboBox<String> roleJComboBox;
    private javax.swing.JLabel roleJL;
    private javax.swing.JLabel welcomeAdminJL;
    // End of variables declaration//GEN-END:variables
}
